// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgfcufbfclvejvyypfxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNnZmN1ZmJmY2x2ZWp2eXlwZnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDg1MzksImV4cCI6MjA2MDMyNDUzOX0.M5OlPvF0C2zVNgOomMaYdASNG5gJCZfytlKuOkj-hog";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);